accepted = [
    "Apache-2.0",
    "BSD-3-Clause",
    "EUPL-1.2",
    "GPL-3.0",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnu"]
ignore-build-dependencies = true
ignore-dev-dependencies = true
filter-noassertion = true
