[package]
name = "warp"
license = "GPL-3.0"
version = "0.4.0"
authors = ["Fina Wilke <code@felinira.net>"]
homepage = "https://apps.gnome.org/app/app.drey.Warp/"
repository = "https://gitlab.gnome.org/World/warp/"
edition = "2021"
default-run = "warp"

[package.metadata.urls]
issuetracker = "https://gitlab.gnome.org/World/warp/issues"
contact = "https://matrix.to/#/#warp:gnome.org"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
once_cell = "1.9"
gtk = {version = "0.6", package = "gtk4", features = ["xml_validation"]}
gdk = {version = "0.6", package = "gdk4", features = ["v4_6"]}
gio = {version = "0.17", package = "gio", features = ["v2_70"]}
adw = {version = "0.3", package = "libadwaita", features = ["v1_3"]}
glib = "0.17"
#gtk = {version = "0.5", package = "gtk4", git = "https://github.com/gtk-rs/gtk4-rs"}
#gdk = {version = "0.5", package = "gdk4", git = "https://github.com/gtk-rs/gtk4-rs", features = ["v4_6"]}
#gio = {version = "0.16", package = "gio", git = "https://github.com/gtk-rs/gtk-rs-core", features = ["v2_70"]}
#adw = {version = "0.2", package = "libadwaita", git = "https://gitlab.gnome.org/World/Rust/libadwaita-rs.git", features = ["v1_2"]}
async-channel = "1.6"
wormhole = { package = "magic-wormhole", version = "0.6" }
futures = "0.3"
url = "2.2"
urlencoding = "2.1"
smol = "1.2"
scopeguard = "1.1"
serde = "1.0"
serde_json = "1.0"
simple_moving_average = "0.1"
chrono = "0.4"
regex = "1.5"
gvdb = { version = "0.4", features = [ "gresource" ]}
gvdb-macros = { version = "0.1" }
thiserror = "1.0"
tempfile = "3.4.0"
backtrace = "0.3"
qrcode = "0.12"
zip = "0.5"
zip-extensions = "0.6"
zbus = "3.3"
async-broadcast = "0.5"

[target.'cfg(windows)'.dependencies]
win32console = "0.1"

[build-dependencies]
xml-rs = "0.8"
walkdir = "2"

[features]
meson = []
