[package]
name = "warp"
version = "0.1.0"
authors = ["Fina Wilke <code@felinira.net>"]
edition = "2021"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
once_cell = "1.9"
gtk = {version = "0.4", package = "gtk4"}
adw = {version = "0.1.0", package = "libadwaita"}
async-channel = "1.6.1"
custom_error = "1.9.2"
wormhole = { git = "https://github.com/magic-wormhole/magic-wormhole.rs", package = "magic-wormhole", version = "0.3.0"}
pretty-bytes = "0.2.2"
futures = "0.3.21"
url = "2.2.2"
async-std = "1.10.0"

[build-dependencies]
xml-rs = "0.8"
walkdir = "2"