[package]
name = "warp"
license = "GPL-3.0"
version = "0.1.0"
authors = ["Fina Wilke <code@felinira.net>"]
homepage = "https://gitlab.gnome.org/felinira/warp/"
repository = "https://gitlab.gnome.org/felinira/warp/"
edition = "2021"
default-run = "warp"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
once_cell = "1.9"
gtk = {version = "0.4", package = "gtk4"}
gio = {version = "0.15.10", package = "gio", features = ["v2_70"]}
adw = {version = "0.1.0", package = "libadwaita"}
async-channel = "1.6.1"
custom_error = "1.9.2"
wormhole = { git = "https://github.com/magic-wormhole/magic-wormhole.rs", package = "magic-wormhole", branch = "dev", version = "0.4.0" }
futures = "0.3.21"
url = "2.2.2"
smol = "1.2.5"
scopeguard = "1.1.0"
serde = "1.0.136"
serde_json = "1.0.79"
simple_moving_average = "0.1.2"
chrono = "0.4.19"
regex = "1.5.5"
gvdb-macros = "0.1.1"

[build-dependencies]
xml-rs = "0.8"
walkdir = "2"