[package]
name = "warp"
license = "GPL-3.0"
version = "0.1.2"
authors = ["Fina Wilke <code@felinira.net>"]
homepage = "https://apps.gnome.org/"
repository = "https://gitlab.gnome.org/World/warp/"
edition = "2021"
default-run = "warp"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
once_cell = "1.9"
gtk = {version = "0.4", package = "gtk4"}
gdk = {version = "0.4.7", package = "gdk4", features = ["v4_6"]}
gio = {version = "0.15.10", package = "gio", features = ["v2_70"]}
adw = {version = "0.1.0", package = "libadwaita"}
async-channel = "1.6.1"
wormhole = { package = "magic-wormhole", version = "0.5.0" }
futures = "0.3.21"
url = "2.2.2"
urlencoding = "2.1.0"
smol = "1.2.5"
scopeguard = "1.1.0"
serde = "1.0.136"
serde_json = "1.0.79"
simple_moving_average = "0.1.2"
chrono = "0.4.19"
regex = "1.5.5"
gvdb = { version = "0.2.0", features = [ "gresource" ]}
gvdb-macros = { version = "0.1.3" }
thiserror = "1.0.31"
tempfile = "3.3.0"
backtrace = "0.3.65"
qrcode = "0.12.0"
zip = "0.5.13"
zip-extensions = "0.6.1"

[build-dependencies]
xml-rs = "0.8"
walkdir = "2"

[features]
meson = []
