[licenses]
version = 2
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "MPL-2.0",
    "GPL-3.0",
    "BSD-3-Clause",
    "ISC",
    "EUPL-1.2",
    "Unlicense",
    "Unicode-DFS-2016",
    "LicenseRef-ring",
]

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
