[advisories]
unmaintained = "workspace"

[licenses]
version = 2
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-3-Clause",
    "EUPL-1.2",
    "GPL-3.0",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
    "ISC",
]
