accepted = [
    "Apache-2.0",
    "MIT",
    "MPL-2.0",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "GPL-3.0",
    "Unlicense",
    "EUPL-1.2",
    "OpenSSL",
]
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnu"]
ignore-build-dependencies = true
ignore-dev-dependencies = true
workarounds = ["ring", "rustls"]
filter-noassertion = true
