[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/magic-wormhole/magic-wormhole.rs"]
git = "https://github.com/magic-wormhole/magic-wormhole.rs"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "cargo/vendor"

[net]
offline = true
